### ISSUE TITLE
VASP OUTCAR parsing sometimes fail

### ISSUE THREAD

**Issue by ondracka** [ondracka/electronic-parsers#21]
I've opened an upstream issue, but it turned out they were aware of it already, just nobody had time to look into it.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/nomad/processing/data.py", line 1507, in parsing
    parser.parse(
  File "/usr/local/lib/python3.11/site-packages/nomad/parsing/parser.py", line 463, in parse
    self.mainfile_parser.parse(mainfile, archive, logger)
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2336, in parse
    self.parse_configurations()
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2242, in parse_configurations
    parse_eigenvalues(n)
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 2044, in parse_eigenvalues
    eigenvalues = self.parser.get_eigenvalues(n_calc)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/electronicparsers/vasp/parser.py", line 876, in get_eigenvalues
    n_eigs = len(eigenvalues) // (self.ispin * n_kpts)
             ~~~~~~~~~~~~~~~~~^^~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: integer division or modulo by zero
```

@SimonKratochvil this is kind of different from the previous tasks, you will have to start at the problematic line in the parser and than try to trace back what is going on... obviously either `self.ispin` is zero (that means the parser was not able to figure out if this is a spin-polarized calculation or not) or `n_kpts` is zero (number of k-points was not properly parsed somewhere). So you need to find out where it was supposed to be parsed and why it went wrong... This was working at some point, so I would assume the fix could be trivial, but the diagnosis might take some time. Be aware that the VASP parser actually support parsign of three different outputs (OUTCAR plain text file, which is where we hit this case, vasprun.xml and also hdf5 files), so don't get too confused if some things look like they are parsed multiple times. Let me know if you need some help.

You can try to use an debugger like for example https://docs.python.org/3/library/pdb.html , but that might take some time to get used to and understand how to actually work with it, and sticking a bunch of prints around will work and I do it is as well most times :smile: although its not a proper developers way :shrug: 

See the original issue
https://github.com/nomad-coe/electronic-parsers/issues/209
and also my duplicate with a reproducer:
https://github.com/nomad-coe/electronic-parsers/issues/246

**Comment by ondracka** [comment]
@jfrodlova actually when you have some time could you look into this?

**Comment by jfrodlova** [comment]
From now on. :) Sorry for the delay

**Comment by jfrodlova** [comment]
@ondracka 
`n_kpts` = 0, because `kpoints_info` dictionary is empty. This dictionary cannot get `'kpoints'`, because this `'kpoints'` quantity (`OutcarTextParser`) has a regex which works for older versions (2013) of OUTCAR files. Newer versions (2017) do not contain phrase `'Following reciprocal coordinates...'`. The thing is that it looks like the newer versions does not include data in this format at all. I only found `'k-points in units of 2pi/SCALE and weight'` or `'k-points in reciprocal lattice and weights'`, but this was also in older versions and it looks like something different.

**Comment by jfrodlova** [comment]
By the way, I noticed a bug in the regex of `'energies'` quantity in `OutcarTextParser`.  Shall I open a PR in upstream for that?

**Comment by ondracka** [comment]
Thanks Jitka, can you link some OUTCAR from the older version which has the `Following reciprocal coordinates...` so I can check the difference? I can't find anything right now.

In theory _reciprocal coordinates_ and _k-points in reciprocal lattice_ should be the same thing, but I'm not that familiar with VASP anymore...

**Comment by ondracka** [comment]
> By the way, I noticed a bug in the regex of `'energies'` quantity in `OutcarTextParser`. Shall I open a PR in upstream for that?

It would be appreciated, but I'm sure you now have other things to do, so unless you already have a patch with test, I think opening a bug in this repo (or upstream) and detailing the findings should be enough.

**Comment by jfrodlova** [comment]
I used OUTCAR from tests/data/vasp/AgAc_relax.

**Comment by ondracka** [comment]
> I used OUTCAR from tests/data/vasp/AgAc_relax.

Thanks, now I see the difference, I believe I need to discuss with VASP guys how this should be done. Anyway thank a lot for all the help. And best of luck whatever you will do next.
